// Do not edit. This file is machine generated by the Resource DLL Wizard.
//---------------------------------------------------------------------------
#define PACKAGE __declspec(package)
#define USERC(FileName) extern PACKAGE _Dummy
#define USERES(FileName) extern PACKAGE _Dummy
#define USEFORMRES(FileName, FormName, AncestorName) extern PACKAGE _Dummy
#pragma hdrstop
int _turboFloat;
//---------------------------------------------------------------------------
/*ITE*/ /*LCID:00000C0A:00000409*/ /**/
/*ITE*/ /*DFMFileType*/ /*src\Boole1\NuevoSC.dfm*/
/*ITE*/ /*DFMFileType*/ /*src\Boole1\app.dfm*/
/*ITE*/ /*DFMFileType*/ /*src\Boole1\calc.dfm*/
/*ITE*/ /*DFMFileType*/ /*src\Boole1\uKarnaugh.dfm*/
/*ITE*/ /*DFMFileType*/ /*src\Boole1\ExpBool.dfm*/
/*ITE*/ /*DFMFileType*/ /*src\Boole1\FormasN.dfm*/
/*ITE*/ /*DFMFileType*/ /*src\Boole1\FormSimp.dfm*/
/*ITE*/ /*DFMFileType*/ /*src\Boole1\Main.dfm*/
/*ITE*/ /*DFMFileType*/ /*src\Boole1\NandNor.dfm*/
/*ITE*/ /*DFMFileType*/ /*src\Boole1\NuevoSC.dfm*/
/*ITE*/ /*DFMFileType*/ /*src\Boole1\SCCompac.dfm*/
/*ITE*/ /*DFMFileType*/ /*src\Boole1\TVComple.dfm*/
/*ITE*/ /*DFMFileType*/ /*src\Boole1\TVManual.dfm*/
/*ITE*/ /*DFMFileType*/ /*src\Boole2\FCalculando.dfm*/
/*ITE*/ /*DFMFileType*/ /*src\Boole2\ayuda.dfm*/
/*ITE*/ /*DFMFileType*/ /*src\Boole2\uLog.dfm*/
/*ITE*/ /*DFMFileType*/ /*src\Boole2\Unit15.dfm*/
/*ITE*/ /*DFMFileType*/ /*src\Boole2\Unit11.dfm*/
/*ITE*/ /*DFMFileType*/ /*src\Boole2\Unit12.dfm*/
/*ITE*/ /*DFMFileType*/ /*src\Boole2\Unit13.dfm*/
/*ITE*/ /*DFMFileType*/ /*src\Boole2\Unit14.dfm*/
/*ITE*/ /*DFMFileType*/ /*src\Boole2\Unit10.dfm*/
/*ITE*/ /*DFMFileType*/ /*src\Boole2\V_Boole2.dfm*/
/*ITE*/ /*DFMFileType*/ /*src\Boole2\Unit2.dfm*/
/*ITE*/ /*DFMFileType*/ /*src\Boole2\Unit3.dfm*/
/*ITE*/ /*DFMFileType*/ /*src\Boole2\Unit4.dfm*/
/*ITE*/ /*DFMFileType*/ /*src\Boole2\Unit5.dfm*/
/*ITE*/ /*DFMFileType*/ /*src\Boole2\Unit6.dfm*/
/*ITE*/ /*DFMFileType*/ /*src\Boole2\Unit8.dfm*/
/*ITE*/ /*DFMFileType*/ /*src\Boole2\Unit9.dfm*/
/*ITE*/ /*DFMFileType*/ /*src\Boole2\uSimulacion.dfm*/
/*ITE*/ /*DFMFileType*/ /*src\Boole2\Unit16.dfm*/
/*ITE*/ /*DFMFileType*/ /*src\Circuito\V_Imprimir.dfm*/
/*ITE*/ /*DFMFileType*/ /*src\Circuito\V_Circuito.dfm*/
/*ITE*/ /*DFMFileType*/ /*src\Comun\uTextoAsoc.dfm*/
/*ITE*/ /*DFMFileType*/ /*src\Boole1\Weblab.dfm*/
/*ITE*/ /*RCFileType*/ /*src\res\mensajes.rc*/
/*ITE*/ /*RCFileType*/ /*exe\boole_DRC.rc*/
//---------------------------------------------------------------------------
USEFORMRES("src\Boole1\NuevoSC.dfm", TForm);
#pragma resource "src\Boole1\NuevoSC.dfm"
USEFORMRES("src\Boole1\app.dfm", TForm);
#pragma resource "src\Boole1\app.dfm"
USEFORMRES("src\Boole1\calc.dfm", TForm);
#pragma resource "src\Boole1\calc.dfm"
USEFORMRES("src\Boole1\uKarnaugh.dfm", TForm);
#pragma resource "src\Boole1\uKarnaugh.dfm"
USEFORMRES("src\Boole1\ExpBool.dfm", TForm);
#pragma resource "src\Boole1\ExpBool.dfm"
USEFORMRES("src\Boole1\FormasN.dfm", TForm);
#pragma resource "src\Boole1\FormasN.dfm"
USEFORMRES("src\Boole1\FormSimp.dfm", TForm);
#pragma resource "src\Boole1\FormSimp.dfm"
USEFORMRES("src\Boole1\Main.dfm", TForm);
#pragma resource "src\Boole1\Main.dfm"
USEFORMRES("src\Boole1\NandNor.dfm", TForm);
#pragma resource "src\Boole1\NandNor.dfm"
USEFORMRES("src\Boole1\NuevoSC.dfm", TForm);
#pragma resource "src\Boole1\NuevoSC.dfm"
USEFORMRES("src\Boole1\SCCompac.dfm", TForm);
#pragma resource "src\Boole1\SCCompac.dfm"
USEFORMRES("src\Boole1\TVComple.dfm", TForm);
#pragma resource "src\Boole1\TVComple.dfm"
USEFORMRES("src\Boole1\TVManual.dfm", TForm);
#pragma resource "src\Boole1\TVManual.dfm"
USEFORMRES("src\Boole2\FCalculando.dfm", TForm);
#pragma resource "src\Boole2\FCalculando.dfm"
USEFORMRES("src\Boole2\ayuda.dfm", TForm);
#pragma resource "src\Boole2\ayuda.dfm"
USEFORMRES("src\Boole2\uLog.dfm", TForm);
#pragma resource "src\Boole2\uLog.dfm"
USEFORMRES("src\Boole2\Unit15.dfm", TForm);
#pragma resource "src\Boole2\Unit15.dfm"
USEFORMRES("src\Boole2\Unit11.dfm", TForm);
#pragma resource "src\Boole2\Unit11.dfm"
USEFORMRES("src\Boole2\Unit12.dfm", TForm);
#pragma resource "src\Boole2\Unit12.dfm"
USEFORMRES("src\Boole2\Unit13.dfm", TForm);
#pragma resource "src\Boole2\Unit13.dfm"
USEFORMRES("src\Boole2\Unit14.dfm", TForm);
#pragma resource "src\Boole2\Unit14.dfm"
USEFORMRES("src\Boole2\Unit10.dfm", TForm);
#pragma resource "src\Boole2\Unit10.dfm"
USEFORMRES("src\Boole2\V_Boole2.dfm", TForm);
#pragma resource "src\Boole2\V_Boole2.dfm"
USEFORMRES("src\Boole2\Unit2.dfm", TForm);
#pragma resource "src\Boole2\Unit2.dfm"
USEFORMRES("src\Boole2\Unit3.dfm", TForm);
#pragma resource "src\Boole2\Unit3.dfm"
USEFORMRES("src\Boole2\Unit4.dfm", TForm);
#pragma resource "src\Boole2\Unit4.dfm"
USEFORMRES("src\Boole2\Unit5.dfm", TForm);
#pragma resource "src\Boole2\Unit5.dfm"
USEFORMRES("src\Boole2\Unit6.dfm", TForm);
#pragma resource "src\Boole2\Unit6.dfm"
USEFORMRES("src\Boole2\Unit8.dfm", TForm);
#pragma resource "src\Boole2\Unit8.dfm"
USEFORMRES("src\Boole2\Unit9.dfm", TForm);
#pragma resource "src\Boole2\Unit9.dfm"
USEFORMRES("src\Boole2\uSimulacion.dfm", TForm);
#pragma resource "src\Boole2\uSimulacion.dfm"
USEFORMRES("src\Boole2\Unit16.dfm", TForm);
#pragma resource "src\Boole2\Unit16.dfm"
USEFORMRES("src\Circuito\V_Imprimir.dfm", TForm);
#pragma resource "src\Circuito\V_Imprimir.dfm"
USEFORMRES("src\Circuito\V_Circuito.dfm", TForm);
#pragma resource "src\Circuito\V_Circuito.dfm"
USEFORMRES("src\Comun\uTextoAsoc.dfm", TForm);
#pragma resource "src\Comun\uTextoAsoc.dfm"
USEFORMRES("src\Boole1\Weblab.dfm", TForm);
#pragma resource "src\Boole1\Weblab.dfm"
USERC("src\res\mensajes.rc");
USERC("exe\boole_DRC.rc");
//---------------------------------------------------------------------------
#define DllEntryPoint
