// Do not edit. This file is machine generated by the Resource DLL Wizard.
//---------------------------------------------------------------------------
#define PACKAGE __declspec(package)
#define USERC(FileName) extern PACKAGE _Dummy
#define USERES(FileName) extern PACKAGE _Dummy
#define USEFORMRES(FileName, FormName, AncestorName) extern PACKAGE _Dummy
#pragma hdrstop
int _turboFloat;
//---------------------------------------------------------------------------
/*ITE*/ /*LCID:00000C0A:0000042D*/ /**/
/*ITE*/ /*RCFileType*/ /*src\res\mensajes.rc*/
//---------------------------------------------------------------------------
USERC("src\res\mensajes.rc");
//---------------------------------------------------------------------------
#define DllEntryPoint
