// Do not edit. This file is machine generated by the Resource DLL Wizard.
//---------------------------------------------------------------------------
#define PACKAGE __declspec(package)
#define USERC(FileName) extern PACKAGE _Dummy
#define USERES(FileName) extern PACKAGE _Dummy
#define USEFORMRES(FileName, FormName, AncestorName) extern PACKAGE _Dummy
#pragma hdrstop
int _turboFloat;
//---------------------------------------------------------------------------
/*ITE*/ /*LCID:00000C0A:0000042D*/ /**/
/*ITE*/ /*DFMFileType*/ /*src\Boole1\FormasN.dfm*/
/*ITE*/ /*RCFileType*/ /*exe\boole_DRC.rc*/
/*ITE*/ /*RCFileType*/ /*src\res\mensajes.rc*/
//---------------------------------------------------------------------------
#pragma resource "src\Boole1\app.dfm"
#pragma resource "src\Boole1\calc.dfm"
#pragma resource "src\Boole1\uKarnaugh.dfm"
#pragma resource "src\Boole1\ExpBool.dfm"
USEFORMRES("src\Boole1\FormasN.dfm", TForm);
#pragma resource "src\Boole1\FormasN.dfm"
#pragma resource "src\Boole1\FormSimp.dfm"
#pragma resource "src\Boole1\Main.dfm"
#pragma resource "src\Boole1\NandNor.dfm"
#pragma resource "src\Boole1\NuevoSC.dfm"
#pragma resource "src\Boole1\SCCompac.dfm"
#pragma resource "src\Boole1\TVComple.dfm"
#pragma resource "src\Boole1\TVManual.dfm"
#pragma resource "src\Boole2\FCalculando.dfm"
#pragma resource "src\Boole2\ayuda.dfm"
#pragma resource "src\Boole2\uLog.dfm"
#pragma resource "src\Boole2\Unit15.dfm"
#pragma resource "src\Boole2\Unit11.dfm"
#pragma resource "src\Boole2\Unit12.dfm"
#pragma resource "src\Boole2\Unit13.dfm"
#pragma resource "src\Boole2\Unit14.dfm"
#pragma resource "src\Boole2\Unit10.dfm"
#pragma resource "src\Boole2\V_Boole2.dfm"
#pragma resource "src\Boole2\Unit2.dfm"
#pragma resource "src\Boole2\Unit3.dfm"
#pragma resource "src\Boole2\Unit4.dfm"
#pragma resource "src\Boole2\Unit5.dfm"
#pragma resource "src\Boole2\Unit6.dfm"
#pragma resource "src\Boole2\Unit8.dfm"
#pragma resource "src\Boole2\Unit9.dfm"
#pragma resource "src\Boole2\uSimulacion.dfm"
#pragma resource "src\Boole2\Unit16.dfm"
#pragma resource "src\Circuito\V_Imprimir.dfm"
#pragma resource "src\Circuito\V_Circuito.dfm"
#pragma resource "src\Comun\uTextoAsoc.dfm"
USERC("exe\boole_DRC.rc");
USERC("src\res\mensajes.rc");
//---------------------------------------------------------------------------
#define DllEntryPoint
