//---------------------------------------------------------------------------


#include <vcl/printers.hpp>
#include <vcl/vcl.h>
#pragma hdrstop
#include "Unit15.h"
#include "V_Boole2.h"

#include <string>
#include <sstream>

#include <time>

#include <windows.h>

#include "Weblab.h"
//---------------------------------------------------------------------------
#pragma resource "*.dfm"
TWeblabForm *WeblabForm;
//---------------------------------------------------------------------------
__fastcall TWeblabForm::TWeblabForm(TComponent* Owner)
        : TForm(Owner)
{
}
//---------------------------------------------------------------------------

using namespace std;

// Get current date/time, format is YYYY-MM-DD.HH:mm:ss
const std::string CurrentDateTime() {
    time_t     now = time(0);
    struct tm  tstruct;
    char       buf[80];
    tstruct = *localtime(&now);
    // Visit http://en.cppreference.com/w/cpp/chrono/c/strftime
    // for more information about date/time format
    strftime(buf, sizeof(buf), "%Y-%m-%d %X", &tstruct);

    return buf;
}


//! Builds a header with the timestamp and additional information, to
//! preppend in generated VHDL code.
std::string BuildCodeHeader()
{
  // Get the computer name
  DWORD size;
  char computername[ MAX_COMPUTERNAME_LENGTH ];
  size = MAX_COMPUTERNAME_LENGTH;
  GetComputerName( computername, &size );

  char username [ 300 ];
  size = 300;
  GetUserName( (char*)username, &size );

  std::ostringstream oss;
  oss << "---------------------------------------------------" << std::endl;
  oss << "-- Generated by Boole-Deusto." << std::endl;
  oss << "-- Timestamp: " << CurrentDateTime() << std::endl;
  oss << "-- Computer name: " << computername << std::endl;
  oss << "-- User name: " << username << std::endl;
  oss << "---------------------------------------------------" << std::endl;
  oss << std::endl;
  return oss.str();
}
