// Do not edit. This file is machine generated by the Resource DLL Wizard.
//---------------------------------------------------------------------------
#define PACKAGE __declspec(package)
#define USERC(FileName) extern PACKAGE _Dummy
#define USERES(FileName) extern PACKAGE _Dummy
#define USEFORMRES(FileName, FormName, AncestorName) extern PACKAGE _Dummy
#pragma hdrstop
int _turboFloat;
//---------------------------------------------------------------------------
/*ITE*/ /*LCID:00000C0A:0000042D*/ /**/
/*ITE*/ /*DFMFileType*/ /*Boole1\app.dfm*/
/*ITE*/ /*DFMFileType*/ /*Boole1\ExpBool.dfm*/
/*ITE*/ /*DFMFileType*/ /*Boole1\FormasN.dfm*/
/*ITE*/ /*DFMFileType*/ /*Boole1\FormSimp.dfm*/
/*ITE*/ /*DFMFileType*/ /*Boole1\Main.dfm*/
/*ITE*/ /*DFMFileType*/ /*Boole1\NandNor.dfm*/
/*ITE*/ /*DFMFileType*/ /*Boole1\NuevoSC.dfm*/
/*ITE*/ /*DFMFileType*/ /*Boole1\SCCompac.dfm*/
/*ITE*/ /*DFMFileType*/ /*Boole1\TVComple.dfm*/
/*ITE*/ /*DFMFileType*/ /*Boole1\TVManual.dfm*/
/*ITE*/ /*DFMFileType*/ /*Boole1\uKarnaugh.dfm*/
/*ITE*/ /*DFMFileType*/ /*Boole2\ayuda.dfm*/
/*ITE*/ /*DFMFileType*/ /*Boole2\uLog.dfm*/
/*ITE*/ /*DFMFileType*/ /*Boole2\Unit10.dfm*/
/*ITE*/ /*DFMFileType*/ /*Boole2\Unit11.dfm*/
/*ITE*/ /*DFMFileType*/ /*Boole2\Unit12.dfm*/
/*ITE*/ /*DFMFileType*/ /*Boole2\Unit13.dfm*/
/*ITE*/ /*DFMFileType*/ /*Boole2\Unit14.dfm*/
/*ITE*/ /*DFMFileType*/ /*Boole2\Unit15.dfm*/
/*ITE*/ /*DFMFileType*/ /*Boole2\Unit16.dfm*/
/*ITE*/ /*DFMFileType*/ /*Boole2\Unit2.dfm*/
/*ITE*/ /*DFMFileType*/ /*Boole2\Unit3.dfm*/
/*ITE*/ /*DFMFileType*/ /*Boole2\Unit4.dfm*/
/*ITE*/ /*DFMFileType*/ /*Boole2\Unit5.dfm*/
/*ITE*/ /*DFMFileType*/ /*Boole2\Unit6.dfm*/
/*ITE*/ /*DFMFileType*/ /*Boole2\Unit8.dfm*/
/*ITE*/ /*DFMFileType*/ /*Boole2\Unit9.dfm*/
/*ITE*/ /*DFMFileType*/ /*Boole2\uSimulacion.dfm*/
/*ITE*/ /*DFMFileType*/ /*Boole2\V_Boole2.dfm*/
/*ITE*/ /*DFMFileType*/ /*Circuito\V_Circuito.dfm*/
/*ITE*/ /*DFMFileType*/ /*Circuito\V_Imprimir.dfm*/
/*ITE*/ /*DFMFileType*/ /*Comun\uTextoAsoc.dfm*/
/*ITE*/ /*RCFileType*/ /*res\mensajes.rc*/
/*ITE*/ /*RCFileType*/ /*../exe\Boole_DRC.rc*/
//---------------------------------------------------------------------------
USEFORMRES("Boole1\app.dfm", ap, Form); /* TForm: DesignClass */
#pragma resource "Boole1\app.dfm"
USEFORMRES("Boole1\ExpBool.dfm", ExprBooleana, Form); /* TForm: DesignClass */
#pragma resource "Boole1\ExpBool.dfm"
USEFORMRES("Boole1\FormasN.dfm", FormasNormales, Form); /* TForm: DesignClass */
#pragma resource "Boole1\FormasN.dfm"
USEFORMRES("Boole1\FormSimp.dfm", ExpresionSimp, Form); /* TForm: DesignClass */
#pragma resource "Boole1\FormSimp.dfm"
USEFORMRES("Boole1\Main.dfm", Principal, Form); /* TForm: DesignClass */
#pragma resource "Boole1\Main.dfm"
USEFORMRES("Boole1\NandNor.dfm", NANDyNOR, Form); /* TForm: DesignClass */
#pragma resource "Boole1\NandNor.dfm"
USEFORMRES("Boole1\NuevoSC.dfm", SistemaCombinacionalNuevo, Form); /* TForm: DesignClass */
#pragma resource "Boole1\NuevoSC.dfm"
USEFORMRES("Boole1\SCCompac.dfm", SCFormasCompactas, Form); /* TForm: DesignClass */
#pragma resource "Boole1\SCCompac.dfm"
USEFORMRES("Boole1\TVComple.dfm", TablaVerdadCompleta, Form); /* TForm: DesignClass */
#pragma resource "Boole1\TVComple.dfm"
USEFORMRES("Boole1\TVManual.dfm", TablaVerdadManual, Form); /* TForm: DesignClass */
#pragma resource "Boole1\TVManual.dfm"
USEFORMRES("Boole1\uKarnaugh.dfm", fKarnaugh, Form); /* TForm: DesignClass */
#pragma resource "Boole1\uKarnaugh.dfm"
USEFORMRES("Boole2\ayuda.dfm", fAyuda, Form); /* TForm: DesignClass */
#pragma resource "Boole2\ayuda.dfm"
USEFORMRES("Boole2\uLog.dfm", fLog, Form); /* TForm: DesignClass */
#pragma resource "Boole2\uLog.dfm"
USEFORMRES("Boole2\Unit10.dfm", Form10, Form); /* TForm: DesignClass */
#pragma resource "Boole2\Unit10.dfm"
USEFORMRES("Boole2\Unit11.dfm", Form11, Form); /* TForm: DesignClass */
#pragma resource "Boole2\Unit11.dfm"
USEFORMRES("Boole2\Unit12.dfm", Form12, Form); /* TForm: DesignClass */
#pragma resource "Boole2\Unit12.dfm"
USEFORMRES("Boole2\Unit13.dfm", Form13, Form); /* TForm: DesignClass */
#pragma resource "Boole2\Unit13.dfm"
USEFORMRES("Boole2\Unit14.dfm", Form14, Form); /* TForm: DesignClass */
#pragma resource "Boole2\Unit14.dfm"
USEFORMRES("Boole2\Unit15.dfm", Form15, Form); /* TForm: DesignClass */
#pragma resource "Boole2\Unit15.dfm"
USEFORMRES("Boole2\Unit16.dfm", Form16, Form); /* TForm: DesignClass */
#pragma resource "Boole2\Unit16.dfm"
USEFORMRES("Boole2\Unit2.dfm", Form2, Form); /* TForm: DesignClass */
#pragma resource "Boole2\Unit2.dfm"
USEFORMRES("Boole2\Unit3.dfm", Form3, Form); /* TForm: DesignClass */
#pragma resource "Boole2\Unit3.dfm"
USEFORMRES("Boole2\Unit4.dfm", Form4, Form); /* TForm: DesignClass */
#pragma resource "Boole2\Unit4.dfm"
USEFORMRES("Boole2\Unit5.dfm", Form5, Form); /* TForm: DesignClass */
#pragma resource "Boole2\Unit5.dfm"
USEFORMRES("Boole2\Unit6.dfm", Form6, Form); /* TForm: DesignClass */
#pragma resource "Boole2\Unit6.dfm"
USEFORMRES("Boole2\Unit8.dfm", Form8, Form); /* TForm: DesignClass */
#pragma resource "Boole2\Unit8.dfm"
USEFORMRES("Boole2\Unit9.dfm", Form9, Form); /* TForm: DesignClass */
#pragma resource "Boole2\Unit9.dfm"
USEFORMRES("Boole2\uSimulacion.dfm", fSimulacion, Form); /* TForm: DesignClass */
#pragma resource "Boole2\uSimulacion.dfm"
USEFORMRES("Boole2\V_Boole2.dfm", Form1Boole2, Form); /* TForm: DesignClass */
#pragma resource "Boole2\V_Boole2.dfm"
USEFORMRES("Circuito\V_Circuito.dfm", FormR, Form); /* TForm: DesignClass */
#pragma resource "Circuito\V_Circuito.dfm"
USEFORMRES("Circuito\V_Imprimir.dfm", FormI, Form); /* TForm: DesignClass */
#pragma resource "Circuito\V_Imprimir.dfm"
USEFORMRES("Comun\uTextoAsoc.dfm", fTextoAsoc, Form); /* TForm: DesignClass */
#pragma resource "Comun\uTextoAsoc.dfm"
USERC("res\mensajes.rc");
USERC("../exe\Boole_DRC.rc");
//---------------------------------------------------------------------------
#define DllEntryPoint
